# Generated by Django 5.0.3 on 2025-06-19 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=15)),
                ('account', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblem', models.FileField(upload_to='collage/emblem/')),
                ('image', models.FileField(upload_to='collage/image/')),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=500)),
                ('yt_links', models.CharField(default='/#', max_length=500)),
                ('fb_links', models.CharField(default='/#', max_length=500)),
                ('introduction', models.TextField()),
                ('achievement', models.TextField()),
                ('reason', models.TextField()),
                ('popular_departments', models.TextField()),
                ('info_en', models.CharField(default='', max_length=200)),
                ('city_en', models.CharField(default='', max_length=50)),
                ('country_en', models.CharField(default='', max_length=50)),
                ('introduction_en', models.TextField(default='')),
                ('achievement_en', models.TextField(default='')),
                ('reason_en', models.TextField(default='')),
                ('popular_departments_en', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(default='不公開')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('picture', models.FileField(upload_to='picture/')),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('title_en', models.CharField(default='', max_length=300)),
                ('text_en', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('account', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=25)),
                ('page_id', models.CharField(max_length=50)),
                ('is_send', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('video', models.TextField()),
                ('student_name', models.TextField()),
                ('content', models.TextField()),
                ('title_en', models.TextField(default='')),
                ('content_en', models.TextField(default='')),
                ('student_name_en', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='file/')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(default='', max_length=200)),
                ('price', models.CharField(max_length=15)),
                ('introduce', models.TextField()),
                ('introduce_en', models.TextField(default='')),
                ('details', models.TextField(default='')),
                ('details_en', models.TextField(default='')),
                ('image', models.FileField(upload_to='collage/image/')),
                ('classification', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=300)),
                ('scope', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=300)),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=300)),
                ('client_id', models.CharField(max_length=300)),
                ('client_secret', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
