# Generated by Django 4.2.9 on 2024-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(default='不公開')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.BooleanField(default=False)),
            ],
        ),
    ]
