# Generated by Django 5.0.3 on 2025-06-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_testquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='pdf',
        ),
    ]
