# Generated by Django 4.2.9 on 2024-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('video', models.FileField(upload_to='static/video/')),
                ('student_name', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
