# Generated by Django 4.2.9 on 2024-01-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Testimony',
        ),
    ]
