# Generated by Django 5.0.3 on 2025-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_testquestion_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account',
            new_name='bookid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_send',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
