# Generated by Django 4.2.9 on 2024-01-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_video_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
