# Generated by Django 5.0.3 on 2025-10-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_account_order_bookid_remove_order_is_send_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
