# Generated by Django 4.2.9 on 2024-01-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_testimony_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
