# Generated by Django 4.2.9 on 2024-01-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='picture',
            field=models.FileField(upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.FileField(upload_to='image/'),
        ),
    ]
