# Generated by Django 4.2.9 on 2024-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_testimony_picture_alter_testimony_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblem', models.FileField(upload_to='collage/emblem/')),
                ('image', models.FileField(upload_to='collage/image/')),
                ('name', models.CharField(max_length=30)),
                ('en_name', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=30)),
                ('links', models.TextField()),
                ('introduction', models.TextField()),
                ('popular_departments', models.TextField()),
            ],
        ),
    ]
