# Generated by Django 4.2.9 on 2024-01-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_collage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collage',
        ),
    ]
