# Generated by Django 4.2.9 on 2024-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblem', models.FileField(upload_to='collage/emblem/')),
                ('image', models.FileField(upload_to='collage/image/')),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('achievement', models.TextField()),
                ('reason', models.TextField()),
                ('popular_departments', models.TextField()),
            ],
        ),
    ]
