# Generated by Django 4.2.9 on 2024-01-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='links',
            field=models.CharField(max_length=500),
        ),
    ]
