# Generated by Django 4.2.9 on 2024-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_collage_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='file/')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=15)),
                ('introduce', models.TextField()),
                ('classification', models.CharField(max_length=15)),
            ],
        ),
    ]
