# Generated by Django 4.2.9 on 2024-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('account', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=25)),
                ('page_id', models.CharField(max_length=50)),
            ],
        ),
    ]
