# Generated by Django 4.2.9 on 2024-01-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
