# Generated by Django 4.2.9 on 2024-01-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_order_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
