# Generated by Django 4.2.9 on 2024-01-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_data_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
