# Generated by Django 4.2.10 on 2024-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_is_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=300)),
                ('scope', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=300)),
                ('expires_in', models.CharField(max_length=300)),
                ('refresh_token', models.CharField(max_length=300)),
                ('client_id', models.CharField(max_length=300)),
                ('client_secret', models.CharField(max_length=100)),
            ],
        ),
    ]
