# Generated by Django 4.2.10 on 2024-03-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='content_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimony',
            name='student_name_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimony',
            name='title_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(max_length=300),
        ),
    ]
