# Generated by Django 4.2.10 on 2024-03-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_testimony_content_en_testimony_student_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('picture', models.FileField(upload_to='picture/')),
                ('text', models.TextField()),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
