# Generated by Django 4.2.10 on 2024-03-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='data',
            new_name='date',
        ),
    ]
