# Generated by Django 4.2.10 on 2024-03-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ranking',
            name='title_en',
            field=models.CharField(default='', max_length=300),
        ),
    ]
