# Generated by Django 4.2.10 on 2024-03-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_course_text_en_course_title_en_ranking_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='introduce_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(),
        ),
    ]
