# Generated by Django 4.2.10 on 2024-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_testquestion_introduce_en_testquestion_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='achievement_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collage',
            name='city_en',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='collage',
            name='country_en',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='collage',
            name='fb_links',
            field=models.CharField(default='/#', max_length=500),
        ),
        migrations.AddField(
            model_name='collage',
            name='info_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='collage',
            name='introduction_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collage',
            name='popular_departments_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collage',
            name='reason_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collage',
            name='yt_links',
            field=models.CharField(default='/#', max_length=500),
        ),
    ]
