# Generated by Django 5.0.3 on 2025-04-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_collage_achievement_en_collage_city_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='picture',
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.TextField(),
        ),
    ]
